// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function UpdateTodoStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodoStatus'](arg1, arg2);
}
